CREATE TABLE IF NOT EXISTS `ebird`.`samples` (
  `SAMPLE_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `TAXONOMIC_ORDER` VARCHAR(15) NOT NULL,
  `SAMPLING_EVENT_IDENTIFIER` VARCHAR(12) NOT NULL,
  `OBSERVATION_COUNT`  VARCHAR(10) NOT NULL,
  `LAST_EDITED_DATE` DATETIME NULL,
  `BREEDING_BIRD_ATLAS_CODE` VARCHAR(3) NULL,
  `BREEDING_BIRD_ATLAS_CATEGORY` VARCHAR(3) NULL,
  `AGE_SEX` VARCHAR(45) NULL,
  PRIMARY KEY (`SAMPLE_ID`)) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS  `ebird`.`species` (
  `TAXONOMIC_ORDER` VARCHAR(15) NOT NULL,
  `CATEGORY` VARCHAR(15) NULL,
  `COMMON_NAME` VARCHAR(45) NULL,
  `SCIENTIFIC_NAME` VARCHAR(45) NULL,
  `SUBSPECIES_COMMON_NAME` VARCHAR(45) NULL,
  `SUBSPECIES_SCIENTIFIC_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`TAXONOMIC_ORDER`)) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS  `ebird`.`sites` (
  `LOCALITY_ID` VARCHAR(16) NOT NULL,
  `LATITUDE` DECIMAL(9,6) NULL,
  `LONGITUDE` DECIMAL(9,6) NULL,
  `COUNTRY` VARCHAR(45) NULL,
  `COUNTRY_CODE` VARCHAR(5) NULL,
  `STATE_PROVINCE` VARCHAR(45) NULL,
  `SUBNATIONAL1_CODE` VARCHAR(15) NULL,
  `COUNTY` VARCHAR(45) NULL,
  `SUBNATIONAL2_CODE` VARCHAR(15) NULL,
  `IBA_CODE` VARCHAR(15) NULL,
  `BCR_CODE` VARCHAR(2) NULL,
  `USFWS_CODE` VARCHAR(10) NULL,
  `ATLAS_BLOCK` VARCHAR(10) NULL,
  `LOCALITY_TYPE` VARCHAR(5) NULL,
  PRIMARY KEY (`LOCALITY_ID`)) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS  `ebird`.`checklists` (
  `SAMPLING_EVENT_IDENTIFIER` VARCHAR(12) NOT NULL,
  `LOCALITY_ID` VARCHAR(16) NULL,
  `OBSERVATION_DATE` DATE NULL,
  `TIME_OBSERVATIONS_STARTED` TIME(0) NULL DEFAULT NULL,
  `OBSERVER_ID` VARCHAR(15) NULL,
  `PROTOCOL_TYPE` VARCHAR(45) NULL,
  `PROTOCOL_CODE` VARCHAR(3) NULL,
  `PROJECT_CODE` VARCHAR(15) NULL,
  `DURATION_MINUTES` INT NOT NULL,
  `EFFORT_DISTANCE_KM` DECIMAL(10,3) NULL,
  `EFFORT_AREA_HA` DECIMAL(10,3) NULL,
  `NUMBER_OBSERVERS` INT NULL,
  `ALL_SPECIES_REPORTED` TINYINT NULL,
  `GROUP_IDENTIFIER` VARCHAR(15) NULL,
  `APPROVED` TINYINT NULL,
  `REVIEWED` TINYINT NULL,
  PRIMARY KEY (`SAMPLING_EVENT_IDENTIFIER`)) ENGINE = MYISAM;

#ALTER TABLE sites ADD COLUMN pt POINT;
#UPDATE spatial_table SET pt=POINT(LONGITUDE, LATITUDE);
#ALTER TABLE sites 
#CHANGE COLUMN pt pt GEOMETRY NOT NULL;
#CREATE SPATIAL INDEX ix_sites_pt ON sites(pt);
